<a href="https://colab.research.google.com/github/CurlyCalie/CurlyCalie/blob/main/numpy_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 KB 2.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.concatenate  # (change this)
function2 = np.split
function3 = ???
function4 = ???
function5 = ???

## Function 1 - np.concatenate (change this)

Add some explanation about the function in your own words

In [5]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Explanation about example

In [9]:
# Example 2 - working

# array1 is of shape 2, 2
# array3 is of shape 2, 3
# we will concatenate them on axis  = 1, i.e, columns
# these can be concatenated because they have compatible shapes

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

Explanation about example (why it breaks and how to fix it)

In [17]:
# Why this breaks ?
# when we concatenate an array, they should be of compatible shapes,
# i.e, they should have the same length across each dimension except the dimension used for concatenation
# in this example, we are trying to concatenate arr1 and add2 on axis=0, but they have different lengths for axis = 1

# TO FIX THIS, use axis = 1 or concatenate zeros to arr1 first

arr1 = np.concatenate((arr1, np.zeros((2,1))), axis=1)

In [18]:
np.concatenate((arr1, arr2), axis=0)

array([[ 1.,  2.,  0.],
       [ 3.,  4.,  0.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

Some closing comments about when to use this function.

In [19]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 2 - numpy.split()

this method is used to split numpy array into subarrays
it takes argument - indices_or_functions

if indices_or_functins : is int, then it will split array into n equal parts

if indices_or_functions : is sorted list, splits the array along the entries in the list 

In [21]:
# Example 1 - working
x = np.arange(10)
# print(x)
np.split(x, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

indices_or_functions = 5
array of 10 integers, split in 5 equal parts of 2 elements

In [24]:
# Example 2 - working
np.split(x, [2, 5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

array is first split ad [:2], and then at [3: 3+3] and then [3+3:]

In [25]:
# Example 3 - breaking (to illustrate when it breaks)
np.split(x, 8)

ValueError: ignored

as an array of 10 digits can not be split into 8 equal parts, this gives us a value error
---



Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'



```
# This is formatted as code
```

## Function 3 - numpy.char.compare_chararrays()

do element wise comparison of 2 arrays which have string values, using a specified comparison operator.

comparison operator is passed in via cmp

In [27]:
# Example 1 - working
a = np.array(['c', 'a', 'l', 'i', 'e'])
b = np.array(['l', 'u', 't', 'a', 'p'])

np.compare_chararrays(a, b, '>', rstrip=True)

array([False, False, False,  True, False])

we are doing an element wise comparison of strings in the array, c>l is False, a > u is false, i>a is True .....

In [29]:
# Example 2 - working
sasuke = np.array(['sasuke', 'uchi', 'ha'])
itachi = np.array(['itachi', 'uchi', 'ha'])

np.compare_chararrays(sasuke, itachi, '==', rstrip=True)

array([False,  True,  True])

we are comparing words instead of letters this time, same words will get True, else, False

In [30]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array(['c', 'a', 'l', 'i', 'e'])
b = np.array(['l', 'u', 't', 'a', 'p', 'i'])

np.compare_chararrays(a, b, '>', rstrip=True)

ValueError: ignored

we can not do a string comparison between 2 arrays of different shapes, in order to fix this, we need to remove an element from a, or add an element to b

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'



```
# This is formatted as code
```

## Function 4 - numpy.char.endswith

this function is used to check whether the string in the array has a certain suffix

In [31]:
# Example 1 - working
x = np.array(['mat', 'cat', 'doormat', 'laundromat'])
np.char.endswith(x, 'mat')

array([ True, False,  True,  True])

except cat, all elements in the array end with mat, hence, T, F, T, T

In [32]:
# Example 2 - working
# using start and end

np.char.endswith(x, 'mat', start=2, end=10)

array([False, False,  True,  True])

start and end define the positions at which the comparisons happen, for word 'mat', start=2 would be 't'. And end=10 would not get any more characters.

hence, match is not found in this case

In [33]:
# Example 3 - breaking (to illustrate when it breaks)
y = np.array([1, 2, 3, 4])
np.char.endswith(y, 1)

TypeError: ignored

we can not use non string arrays to compare elements with numbers, to fix this, cast array elements as varchar = ['1', '2', '3'], and search for the varchar element

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 5 - numpy.transpose()

returns an array with transposed axis

In [34]:
# Example 1 - working
x = np.array([['lut', 'fi'], ['cal', 'iph']])
np.transpose(x)

array([['lut', 'cal'],
       ['fi', 'iph']], dtype='<U3')

the matrix has been transposed 

In [35]:
# Example 2 - working
y = np.array(['ca', 'li', 'eee'])

np.transpose(y)

array(['ca', 'li', 'eee'], dtype='<U3')

transposing a 1d array will return the same array

In [46]:
# Example 3 - breaking (to illustrate when it breaks)
z = np.array([['a', 'b', 'c'], ['d', 'e', 'f']])
np.transpose(z, axes=[1, 2])

AxisError: ignored

axes is used for ordering the axes [ when we transpose a matrix, we basically rearrange the order ]

to fix here, put axes=[0, 1] or [1,0]

as axes = 2 does not exist for the input array

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [47]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.
